---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    build: web-ui-ng
  name: web-ui-ng
spec:
  tags:
  - name: latest
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: web-ui-ng
  name: web-ui-ng
spec:
  output:
    to:
      kind: ImageStreamTag
      name: web-ui-ng:latest
  source:
    contextDir: .
    git:
      ref: master
      uri: https://github.com/cvicens/coolstore-ng.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:8
        namespace: openshift
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: web-ui-ng
    version: 1.0.0
  name: web-ui-ng
spec:
  replicas: 1
  selector:
    app: web-ui-ng
    deploymentconfig: web-ui-ng
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: web-ui-ng
        version: 1.0.0
        deploymentconfig: web-ui-ng
    spec:
      serviceAccountName: web-ui
      containers:
      - image: web-ui-ng
        name: web-ui-ng
        env:
          - name: COOLSTORE_GW_ENDPOINT
            value: "${COOLSTORE_GW_ENDPOINT}"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - web-ui-ng
      from:
        kind: ImageStreamTag
        name: web-ui-ng:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-ui-ng
    version: 1.0.0
  name: web-ui-ng
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-ui-ng
    deploymentconfig: web-ui-ng
---
apiVersion: v1
kind: Route
metadata:
  labels:
    expose: "true"
    group: com.redhat.cloudnative
    version: 1.0.0
    app: web-ui-ng
  name: web-ui-ng
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: web-ui-ng